### ISSUE TITLE
Import error with foolbox

### ISSUE THREAD

**Issue by carl24k** [bethgelab/robust-vision-benchmark#12]
Hi. I just installed foolbox and robust_vision_benchmark. When I try to import rbv, I get an error having to do with foolbox. Is this an incompatibility between the latest versions? Is there an earlier version of foolbox that I need?

`(p3env) MacBook-Air-5:biostack home$ python
Python 3.6.5 (default, Apr 25 2018, 14:26:36) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import robust_vision_benchmark as rvb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carl/Documents/biostack/p3env/lib/python3.6/site-packages/robust_vision_benchmark/__init__.py", line 7, in <module>
    from .server import mnist_model_server  # noqa: F401
  File "/Users/carl/Documents/biostack/p3env/lib/python3.6/site-packages/robust_vision_benchmark/server.py", line 17, in <module>
    from .client import BSONModel
  File "/Users/carl/Documents/biostack/p3env/lib/python3.6/site-packages/robust_vision_benchmark/client.py", line 11, in <module>
    from foolbox.models import DifferentiableModel
ImportError: cannot import name 'DifferentiableModel'`

**Comment by jonasrauber** [comment]
The RVB package is not compatible with Foolbox 3 or newer. Foolbox 1 should work. More generally, however, the RVB is not really maintained at the moment.

**Comment by jonasrauber** [comment]
_Solved through direct communication._
